services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: WorldLeague
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - world-league-network
    ports:
      - "5432:5432"
      
  worldleague.web.api:
    build:
      context: .
      dockerfile: aspnet-core/src/Ui/WorldLeague.Web.Api/Dockerfile
    container_name: world-league-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres  
    networks:
      - world-league-network

networks:
  world-league-network:
    driver: bridge

volumes:
  postgres_data:
